### ISSUE TITLE
StdUtils v1.09 InvokeShellVerb (ansi) start menu pin/unpin bug

### ISSUE THREAD

**Issue by andry81** [lordmulder/stdutils#11]
[InvokeShellVerb bug.zip.txt](https://github.com/lordmulder/stdutils/files/59627/InvokeShellVerb.bug.zip.txt)

StdUtils.dll (ansi) version 1.07 works with start menu pinning.
new version 1.09 completely broken, i could not pin anything to startmenu.

OS: Windows 7 64-bit

Please see attachment:
1. download and rename to zip (i could not upload just zip file, have to upload it as text file).
2. edit build.bat for path to NSIS v3 (v20-Mar-2015.cvs)
3. run build.bat
4. prepare OS for Russian codepage/language
5. run test_ansi_1_07.exe and test_ansi_1_09.exe
6. choose russian language from MUI dialog
7. observe different results in gui output

**Comment by lordmulder** [comment]
Seems to work fine for me:
http://sourceforge.net/projects/muldersoft/files/StdUtils-Plugin%20%28NSIS%29/Testing/StdUtils-InvokeShellVerb.2015-12-12.zip/download

Are you sure you are using the **latest** "include" file for v1.09?

**Comment by andry81** [comment]
Your version does not have MUI2 language selection. Try to use different lanugage, for example Russian.

**Comment by lordmulder** [comment]
> Your version does not have MUI2 language selection. Try to use different lanugage, for example Russian.

How is that supposed to change anything?

Anyway, you didn't answer whether you built your installer with the **latest** include (NSH) file.

Also you didn't answers whether the Unicode version works.

Unless these are ruled out, further investigation is void...

**Comment by andry81** [comment]
Re: [stdutils] StdUtils v1.09 InvokeShellVerb (ansi) start menu pin/unpin bug (#11)



Hello LoRd_MuldeR,

Saturday, December 12, 2015, 4:05:21 PM, you wrote:





Seems to work fine for me:
http://sourceforge.net/projects/muldersoft/files/StdUtils-Plugin%20%28NSIS%29/Testing/StdUtils-InvokeShellVerb.2015-12-12.zip/download
Are you sure you are using the latest "include" file for v1.09?
—
Reply to this email directly or view it on GitHub.



yes, i just compared the dll from master branch and the dll from mine example.
your examples does not have language selection and uses english language by default.

-- 
Best regards,
 Andry                            mailto:andry@inbox.ru

**Comment by lordmulder** [comment]
Language doesn't matter, because *InvokeShellVerb* function doesn't take an string arguments.

Internally, the function is *Unicode* all the way. ANSI vs. Unicode only effects the interface between Plugin and NSIS.

If you use StdUtils v1.09, you have to **build** your installer with the ***latest** include (NSH) file!

**Comment by andry81** [comment]
Re: [stdutils] StdUtils v1.09 InvokeShellVerb (ansi) start menu pin/unpin bug (#11)



Hello LoRd_MuldeR,

Saturday, December 12, 2015, 6:15:12 PM, you wrote:

>Your version does not have MUI2 language selection.
Function .onInit
  !insertmacro MUI_LANGDLL_DISPLAY
FunctionEnd

>How is that supposed to change anything?
the function (v1.09) does not work on different language properly, old version (v1.07) has worked, please observer mine attachment in the issue





Anyway, you didn't answer whether you built your installer with the latest include (NSH) file.


i am using the latest and by the way it won't build on previous because defines has changed





Also you didn't answers whether the Unicode version works.


i don't use unicode version, i have many plugins to check/port them on unicode and actually i don't need to




-- 
Best regards,
 Andry                            mailto:andry@inbox.ru

**Comment by andry81** [comment]
Re: [stdutils] StdUtils v1.09 InvokeShellVerb (ansi) start menu pin/unpin bug (#11)



Hello LoRd_MuldeR,

Saturday, December 12, 2015, 6:21:09 PM, you wrote:





Language doesn't matter, because InvokeShellVerb function doesn't take an string arguments.
Internally, the function is Unicode all the way. ANSI vs. Unicode only effects the interface between Plugin and NSIS.


Then why behaviour has changed in v1.09? In v1.07 it works fine. I just updated to new version and shortcuts did break.





If you use StdUtils v1.09, you have to build your installer with the **latest* include (NSH) file!


i did


-- 
Best regards,
 Andry                            mailto:andry@inbox.ru

**Comment by lordmulder** [comment]
Again, the *InvokeShellVerb* function does **not** take any String argument. Internally, the function uses *Unicode* (UTF-16, `whchar_t`) all the way, regardless of whether you use "ANSI" or "Unicode" plug-in.

BTW: If you build your installer as ANSI, all NSIS strings will use the *local* ANSI codepage - whatever that is! If user happens to have Russian codepage configured, then Russion characters can be represented, but (some) German characters can not. Conversely, if user happens to have German codepage configures, the German characters can be represented, but the Russian ones can't! Using ANSI is a very bad idea. This is 2015, not the 1970's ;-)

**Comment by andry81** [comment]
Re: [stdutils] StdUtils v1.09 InvokeShellVerb (ansi) start menu pin/unpin bug (#11)



Hello LoRd_MuldeR,

Saturday, December 12, 2015, 6:48:21 PM, you wrote:





Again, the InvokeShellVerb function does not take any String argument.


${StdUtils.InvokeShellVerb} $0 "$EXEDIR\${TEST_DIR}" "$(SHORTCUT_TEST_${ENC}).lnk" ${STDUTILS_CONST_SHELLVERB_PINTOSTART}

"$EXEDIR\${TEST_DIR}" "$(SHORTCUT_TEST_${ENC}).lnk"
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
String arguments





 Internally, the function uses Unicode (UTF-16, whchar_t) all the way, regardless of whether you use "ANSI" or "Unicode" plug-in.
BTW: If you build your installer as ANSI, all NSIS strings will use the local ANSI codepage - whatever that is!


thats why i am tested utf-8 version strings and it works fine in 1.07





 If user happens to have Russian codepage configured, then Russion characters can be represented, but (some) German characters can not. Conversely, if user happens to have German codepage configures, the German characters can be represented, but the Russian ones can't! Using ANSI is a very bad idea. This is 2015, not the 1970's ;-)


I am not using German characters at all, i am using Russian characters and Russian code page and the function does not work with them.
Anyway, all these does not clarify why the 1.07 works om Russian characters and 1.09 is not.


-- 
Best regards,
 Andry                            mailto:andry@inbox.ru

**Comment by andry81** [comment]
BTW2: Yes, the names of the InvokeShellVerb constants have changed. But if you build an "old" NSI file using the "old" NSH file, it's still going to build. However the values will just be wrong! Once you have ported your NSI file to the "new" NSH file, it will not be able to build with the "old" NSH file, that's right.

Why u won't to just check the attachment to be sure that am i using?

**Comment by lordmulder** [comment]
> BTW: thats why i am tested utf-8 version strings and it works fine in 1.07

There is absolutely **no** support for UTF-8 in NSIS or StdUtils, an especially **not* in the underlying Win32 API's! Windows offers a `char` (ANSI) version of each Win32 API function, which expects String to be encoded in local ANSI Codepage - whatever that happens to be. UTF-8 is **not** going to work! If you want *Unicode*, you have use the `wchar_t` (Wide) version of the function, which uses UTF-16.

> Why u won't to just check the attachment to be sure that am i using?

Because it doesn't tell me anything about what NSH file *you* have used to build the installer on *your* system. That's why I'm giving you advices on what is going to work and what is **not** going to work. Take it or leave it...

**Comment by andry81** [comment]
Re: [stdutils] StdUtils v1.09 InvokeShellVerb (ansi) start menu pin/unpin bug (#11)



Hello LoRd_MuldeR,

Saturday, December 12, 2015, 7:25:19 PM, you wrote:





BTW: thats why i am tested utf-8 version strings and it works fine in 1.07
There is absolutely no support for UTF-8 in NSIS or StdUtils, an especially not* in the underlying Win32 API's! Windows offers a char (ANSI) version of each Win32 API function, which expects String to be encoded in local ANSI Codepage - whatever that happens to be. UTF-8 is **not going to work!


but UTF-8 IS working in 1.07, see log files in the attachment





Why u won't to just check the attachment to be sure that am i using?
Because it doesn't tell me anything about what NSH file you have used to build the installer on your system.


what you are talking about?
!if "${STDUTILS_VER}" = "1.09"
!addincludedir ".\StdUtils_1_09"
!addplugindir ".\StdUtils_1_09"
!include "StdUtils.nsh"
!define STDUTILS_CONST_SHELLVERB_PINTOSTART ${StdUtils.Const.ShellVerb.PinToStart}
!define STDUTILS_CONST_SHELLVERB_UNPINFROMSTART ${StdUtils.Const.ShellVerb.UnpinFromStart}
!define TEST_DIR "test_dir_1_09"
!else
!addincludedir ".\StdUtils_1_07"
!addplugindir ".\StdUtils_1_07"
!include "StdUtils.nsh"
!define STDUTILS_CONST_SHELLVERB_PINTOSTART ${StdUtils.Const.ISV_PinToStartmenu}
!define STDUTILS_CONST_SHELLVERB_UNPINFROMSTART ${StdUtils.Const.ISV_UnpinFromStartmenu}
!define TEST_DIR "test_dir_1_07"
!endif


you can open corresponding folder and check it on yourself





 That's why I'm giving you advices on what is going to work and what is not going to work. Take it or leave it...


i am still don't understand why you still didn't open the attachment

-- 
Best regards,
 Andry                            mailto:andry@inbox.ru

**Comment by lordmulder** [comment]
> but UTF-8 IS working in 1.07, see log files in the attachment

No, it's certainly not!

(See my explanation about Win32 API and UTF-8  in the previous post)

**Comment by andry81** [comment]
Re: [stdutils] StdUtils v1.09 InvokeShellVerb (ansi) start menu pin/unpin bug (#11)



Hello LoRd_MuldeR,

Saturday, December 12, 2015, 7:37:39 PM, you wrote:





but UTF-8 IS working in 1.07, see log files in the attachment
No, it's certainly not!
(See my explanation about Win32 API and UTF-8 in the previous post)


You still didn't test it properly. Run virtual machine under Windows with Russian language set by default to test it properly.


-- 
Best regards,
 Andry                            mailto:andry@inbox.ru

**Comment by andry81** [comment]
>It's horribly unreliable
i don't need it to be reliable, because i don't have conditions for reliability

>And, to make things even worse, you cannot know what characters may happen to be in the user's chosen install path.
Yes, i have: English+Russian - no other language is using.

>As soon as NSIS v3 is stable and we have "official" Unicode support, I'll just drop the ANSI version.
sad to hear it :(

**Comment by lordmulder** [comment]
> Yes, i have: English+Russian - no other language is using.

That's **not** the point. The point is: English+Russian file names work on *your* system with the ANSI version of NSIS, because *your* system happens to have a Russian (Cyrillic) ANSI codepage configured. But you do **not** know and can **not** influence what ANSI codepage the *user* will have configured on *her* system! If, for example, the user happens to have a German (Western European) codepage configured, the *exactly same* file names that worked perfectly fine for youare **not** going to work for the user with the ANSI version of NSIS! If you *do* care about that your installer is actually working for your users, this **is** a big problem! Use the *Unicode* version to get rid of these baste codepage problems!

----------------

> sad to hear it :(

There is **no** point in supporting ANSI, which inherently broken, when a much better solution is available. The first Windows with full Unicode support was Windows 2000, released more than 1.5 decades ago. The only reason to use ANSI would be support for Windows 9x, which is certainly **not** relevant these days. Also, *StdUtils* uses many other Win32 API's that were **not** available in Windows 9x, so we can **not ** get Windows 9x support anyway.

**Comment by andry81** [comment]
Re: [stdutils] StdUtils v1.09 InvokeShellVerb (ansi) start menu pin/unpin bug (#11)



Hello LoRd_MuldeR,

Sunday, December 13, 2015, 4:30:32 PM, you wrote:





Yes, i have: English+Russian - no other language is using.
That's not the point. The point is: English+Russian file names work on your system with the ANSI version of NSIS, because your system happens to have a Russian (Cyrillic) ANSI codepage configured. But you do not know and can not influence what ANSI codepage the user will have configured on her system!


Yes, i know, just believe me.





 If, for example, the user happens to have a German (Western European) codepage configured, the exactly same file names that worked perfectly fine for youare not going to work for the user with the ANSI version of NSIS!


It's should not have to.





 If you do care about that your installer is actually working for your users, this is a big problem!


I don't have to, i do not have those kind of users! I don't solve problems that i won't have.





 Use the Unicode version to get rid of these baste codepage problems!


I am using exactly that i need to. There is much more effort to just use unicode than to just fix single bug in single plugin.





sad to hear it :(
There is no point in supporting ANSI, which inherently broken, when a much better solution is available.


There is if you supporting something. Why i have to port whole plugins tree because someone plugin does not want to work properly with ansi?


-- 
Best regards,
 Andry                            mailto:andry@inbox.ru

**Comment by andry81** [comment]
I've located the bug. In new version (beginning from 1.08) you obscured COM component path usage with your own function - FILE_EXISTS (GetFileAttributes) which obviously has failed. I commented out the call and it's fixed the bug.

**Comment by lordmulder** [comment]
> I've located the bug. In new version (beginning from 1.08) you obscured COM component path usage with your own function - FILE_EXISTS (GetFileAttributes) which obviously has failed.

What?

I did **not ** "obscure" anything. The `FILE_EXISTS` function just checks whether the file you are trying to pin exists. It clearly makes *no* sense trying to pin a file that doesn't exist. So we first check for file existence, and, if the file does *not* exist, we can avoid the whole COM call - as it unavoidably would fail unavoidably anyway.

If `FILE_EXISTS` fails, it means the file either really doesn't exist, or - which is quite possible in the ANSI version - the file's path cannot be represented in your current ANSI codepage. The latter is of course not a problem of the `FILE_EXISTS` function, but a general problem of using ANSI version instead of Unicode.

**Comment by andry81** [comment]
>I did not "obscure" anything.

You <b>are</b> and you know that

>The FILE_EXISTS function just checks whether the file you are trying to pin exists.
I don't care how FILE_EXISTS checks anything, much more important here is that the function obscures COM behaviour, which works fine on UTF-8 paths in ANSI mode.

>If FILE_EXISTS fails, it means the file either really doesn't exist
Of cause not, it depends on COM path parsing logic

**Comment by lordmulder** [comment]
> I don't care how FILE_EXISTS checks anything

Well, you better *do*, as pinning a non-extsing file makes **no** sense. And performing a file existence check as a "shortcut" makes a lot of sense. The COM invocation would unavoidably fail anyway, if file doesn't exist. So, unless you can show that `FILE_EXISTS` doesn't do what it is supposed to do, there certainly is no reason to change anything!

Note that `FILE_EXISTS` is supposed to work with ANSI strings in the ANSI version and it is supposed to work with Unicode (UFT-16) strings in the Unicode version. It is **not** supposed to work with UTF-8 strings, it *never* was supposed to work with UTF-8 strings and it probably never will...

-----------------

> much more important here is that the function obscures COM behaviour, which works fine on UTF-8 paths in ANSI mode.

Nothing has been "obscured" here. The file existence check happens **before** the COM invocation and the actual COM invocation is **100% un-affected** by this. So please stop spreading FUD!

> Of cause not, it depends on COM path parsing logic

No it does **not**. How do you get that strange idea? FILE_EXISTS does **not** use COM in any way.

-----------------

If you are able to read C/C++ code (and Win32 API documentation), then you will see that *all* the relevant COM methods, especially `NameSpace()` and `ParseName()` from `IShellDispatch` COM interface take **BSTR** strings as input.

**BSTR** are strings with an explicit length field, rather than just a NULL terminator. And, even more important, they are **UTF-16** (Unicode) strings. So how does *StdUtils* construct the required BSTR objects for calling the COM functions?

If you look at the code, you'll see that in the **Unicode** plug-in version the BSTR is created "1:1" from the input Unicode (UTF-16) string, of course. And in the **ANSI** version the input ANSI strings is - necessarily! - converted from local ANSI codepage to UTF-16! This is done by calling `ansi_to_utf16()` function! This does **not** work with UTF-8 input strings. This has **never** worked with UTF-8 input strings. This is **never** going to work with UTF-8 strings at any point in the future.

Of course, converting the input strings from local **ANSI** codepage to **UTF-16** is the "correct" thing to do here, because input strings *must* be expected to be encoded in the local ANSI codepage - treating them as UTF-8 would be **wrong** as they generally will **not** be UTF-8, but encoded in the local **ANSI** codepage. That is **not** my idea, but how the NSIS plug-in API has been designed...
