### ISSUE TITLE
x64 version

### ISSUE THREAD

**Issue by systracer** [lordmulder/stdutils#18]
Please add 64-bit version of plugin, even NSIS-x64 already running in pure x64. Thank you very much!

**Comment by lordmulder** [comment]
Sorry, currently I do not have plans for a 64-Bit edition.

This is because:

1. 32-Bit installers run on 32-Bit Windows _and_ on 64-Bit Windows, while 64-Bit installers work on 64-Bit Windows _only_. Also, 64-Bit software can be installed using a 32-Bit installer just fine. Only advantage of going 64-Bit is that more memory (i.e. more than 4 GB) can be addressed in a single process. But, for an installer being able to address more than 4 GB of memory is pretty pointless. So there's **not** much reason for 64-Bit installers to exist, except for VERY specific cases (e.g. "x64 Recovery Environment").

2. AFAIK, there is **no** 64-Bit version of NSIS 2.x, only of the new NSIS 3.x. However, **StdUtils** has always been developed for NSIS 2.x, it is based on NSIS 2.x plug-in API and was tested exclusively with NSIS 2.x. If the current version of StdUtils works with NSIS 3.x (32-Bit) then this is "by luck". Before I even think about 64-Bit, the transition to NSIS 3.x is a necessary precondition. Will do this when I find some time.

3. **StdUtils** is heavily based on `MSVCRT.DLL`, the C-Runtime library that is part of Windows – _**not**_ the VisualStudio-specific one that needs to be installed separately. Unfortunately, modern VisualStudio does **_not_** come with import libraries for `MSVCRT.DLL`. I had to "borrow" the required import library from a very old version of VisualStudio. That old version of VisualStudio did **_not_** even support x64 at all, it was probably released before the first x64 processors were available on the market! So, I do _**not**_ know where to get 64-Bit import libraries for 64-Bit `MSVCRT.DLL`. Do you?

**Comment by systracer** [comment]
Thank you for a clear and detailed answer!
