### ISSUE TITLE
UnpinFromStart and UnpinFromTaskbar don't work when the target file doesn't exist

### ISSUE THREAD

**Issue by alexmitev81** [lordmulder/stdutils#22]
Hello,
I have an issue with the UnpinFromStart and UnpinFromTaskbar commands:
I remove my program first with
`Delete "$INSTDIR\${PROGEXE}"`
however when I later call
`${StdUtils.InvokeShellVerb} $0 "$INSTDIR" "${PROGEXE}" ${StdUtils.Const.ShellVerb.UnpinFromStart}`
I get the error
> not_found

Seems like `UnpinFromStart` requires the target file (`${PROGEXE}` in this case) to exist in order to succeed. But I guess this is not a Windows requirement, because manually un-pinning a link to a program that doesn't exist is successful in Windows. Can this be requirement be removed?

**Comment by lordmulder** [comment]
Hello.

Windows does **not** provide an *official* API to "pin" or "unpin" a file to/from the taskbar 😼

What it _does_ provide (and what we use) is an API to enumerate the available "verbs" (operations) for a certain **_file_**. This is pretty much exactly the same list of operations that you'd see in the context menu in Windows Explorer, when you right-click on the file. We can also execute one of these verbs (operations) via the API.

The whole thing is complicated, because we only get the **_language-specific_** name of the "verb" (operation) via the API, i.e. exactly the text that would be shown to the user in Windows Explorer. This is different in each language of Windows (and may even be different for different Windows versions of the same language). So, we first have to lookup what *pin to start"* or *"unpin from start"* means in the user current language and current Windows version. This we try to lookup via the specified ID from the corresponding resource file.

So, to make a long story short: It all depends the [**`IShellDispatch`**](https://msdn.microsoft.com/en-us//library/windows/desktop/gg537707(v=vs.85).aspx) API, which allows use to get a [`FolderItem`](https://msdn.microsoft.com/en-us/library/windows/desktop/bb787810(v=vs.85).aspx) object corresponding to our target ***file***. On this object, we call the `Verbs` function in order to find the desired operation. Finally, we call the `InvokeVerb` function to actually invoke the operation.

Hence, **no** file, **no** luck. At least I don't know of a way to do it *without* a file :anguished:

Regards,
MuldeR

**Comment by alexmitev81** [comment]
Thank you for the detailed report, MuldeR.
Then I will have to update my scripts to delete the links first **before** the file.
Regards,
Alex

**Comment by alexmitev81** [comment]
P.S. Maybe it's a good idea to mention somewhere that the (un)pin functions require an existing file. For me it was not obvious, and I was wondering why my script failed, but the demo (using `$SYSTEM\mspaint.exe`, which always exists) worked.

Regards,
Alex
