### ISSUE TITLE
Add version info (date of last commit) to Include\StdUtils.nsh

### ISSUE THREAD

**Issue by Tobias-B-Besemer** [lordmulder/stdutils#25]
I think you should add a version info (date of last commit?) to Include\StdUtils.nsh.

Reason:
We use in BleachBit (https://github.com/bleachbit/bleachbit) the NSIS Plugin NsisMultiUser (https://github.com/Drizin/NsisMultiUser). For version management of the single PR & branches it would be helpful to know the version of stdutils used.

**Comment by lordmulder** [comment]
Hello.

We already have a function in **`StdUtils.nsh`** that returns the version of the Plugin:
[${StdUtils.GetLibVersion}](http://muldersoft.com/docs/stdutils_readme.html#14863bf9)

Or do you request that we store the version *directly* in `StdUtils.nsh`, as a **`!define`** ❓ 

I don't think it would make a lot of sense to store the "normal" version in the include file (`StdUtils.nsh`), because the public API specified in that include file does **not** change in every release of the plug-in DLL. Normally, the same `StdUtils.nsh` will work with *different* versions of the plug-in DLL. The `StdUtils.nsh` only needs to be updated when the public API of the plug-in DLL changes. So, maybe we could **`!define`** a separate *API version* in the include file.

Regards
MuldeR

**Comment by Tobias-B-Besemer** [comment]
Would work for me!

But a simple comment in StdUtils.nsh that shows the version of StdUtils.nsh would work for me, too.

As short explanation, again:
I write/wrote a new installer for https://github.com/bleachbit/bleachbit. The installer for BB use https://github.com/Drizin/NsisMultiUser. And NsisMultiUser again use StdUtils.
Therefor a function in StdUtils.nsh doesn't help me much, because StdUtils.nsh gets triggered by NsisMultiUser...
But to get sure that e.g. all files in all work folders for each PR are up-to-date, a version info in the file would be helpful... (...just something a coder sees immediately, when he opens the file with an editor...)

**Comment by lordmulder** [comment]
Okay, feel free to try with this version:
[**StdUtils.2019-11-22.zip**](https://github.com/lordmulder/stdutils/files/3879411/StdUtils.2019-11-22.zip)

**Comment by Tobias-B-Besemer** [comment]
Works perfect for me! :)
Thx 4 the add! :)
