### ISSUE TITLE
Windows 10 detection

### ISSUE THREAD

**Issue by pschrijver** [lordmulder/stdutils#9]
Hi,
The detection of Windows 10 currently isn't correct. When using the latest insider preview (build 10130) the version of Windows gets detected as Windows 8 (NT 6.2).

![windows10](https://cloud.githubusercontent.com/assets/3215314/8033258/31cd1650-0ddd-11e5-9183-c6c55a1c4d15.png)

**Comment by lordmulder** [comment]
Starting with Windows 8.1, Microsoft made the **braindead** decision to break the ``GetVersionEx()`` API. So this API will now report **wrong** results to the calling application &ndash; unless you include some special GUID in the Manifest. But since the required GUID is *different* for each Windows version and Microsoft doesn't reveal the required GUID for *future* Windows versions until they actually are released, it means that now ``GetVersionEx()`` will effectively report the Windows version that the program has been compiled for &ndash; **not** the Windows version we are actually running on! And since you already know which Windows version you compiled your program for (you don't need to call the Win32 API for this!), the function effectively is a **NOP** now! Yes, it's really as **braindead** as it sounds. Microsoft totally ruined the version API.

Until now, there was a *workaround* to detect the **actual** Windows version that we are running on. We could still use the ``VerifyVersionInfo()`` function. This function is not really intended to *detect* a version number, but it could be used in a "smart" way to reveal the **true** version number. Under Windows 8/8.1 this has been working fine and it's exactly what StdUtils does. If Microsoft &ndash; in another act of insanity &ndash; has now broken ``VerifyVersionInfo()`` too, there will be no more way to detect the **true** Windows version! If so, please don't blame me!

**Comment by pschrijver** [comment]
Oh wow, I had no idea Microsoft screwed this up so badly. Let's hope the release version of Windows 10 still has some way of detecting the version. Thanks for the info.

**Comment by lordmulder** [comment]
Okay, I have been able to make some more tests today.

I have put together a little test program, which you can download here:
[**GetRealOSVersion.2015-06-13.zip**](http://muldersoft.com/temp/GetRealOSVersion.2015-06-13.zip)

-----------

**Windows 7** reports faithfully:

	GetRealOSVersion [Jun 13 2015]
	==============================

	Actual KERNEL32.DLL Version: 6.1.7601.18869

	GetVersionEx() has reprted: v6.1 (SP-1)

	Testing v7.0 (SP-0) with VerifyVersionInfoW()
	--> NOT supported!
	Testing v8.0 (SP-0) with VerifyVersionInfoW()
	--> NOT supported!
	Testing v9.0 (SP-0) with VerifyVersionInfoW()
	--> NOT supported!
	Testing v10.0 (SP-0) with VerifyVersionInfoW()
	--> NOT supported!
	Testing v6.2 (SP-0) with VerifyVersionInfoW()
	--> NOT supported!
	Testing v6.1 (SP-2) with VerifyVersionInfoW()
	--> NOT supported!

	Completed: Running on Windows v6.1 (SP-1)

-----------

**Windows 8.1** lies to us, but the ``VerifyVersionInfo()`` hack works:

	GetRealOSVersion [Jun 13 2015]
	==============================

	Actual KERNEL32.DLL Version: 6.3.9600.17415

	GetVersionEx() has reprted: v6.2 (SP-0)

	Testing v7.0 (SP-0) with VerifyVersionInfoW()
	--> NOT supported!
	Testing v8.0 (SP-0) with VerifyVersionInfoW()
	--> NOT supported!
	Testing v9.0 (SP-0) with VerifyVersionInfoW()
	--> NOT supported!
	Testing v10.0 (SP-0) with VerifyVersionInfoW()
	--> NOT supported!
	Testing v6.3 (SP-0) with VerifyVersionInfoW()
	--> supported
	Testing v6.4 (SP-0) with VerifyVersionInfoW()
	--> NOT supported!
	Testing v6.3 (SP-1) with VerifyVersionInfoW()
	--> NOT supported!

	Completed: Running on Windows v6.3 (SP-0)

-----------

**Windows 10** (Build 10130) is beyond repair, they made ``VerifyVersionInfo()`` *useless* too:

	GetRealOSVersion [Jun 13 2015]
	==============================

	Actual KERNEL32.DLL Version: 10.0.10130.0

	GetVersionEx() has reprted: v6.2 (SP-0)

	Testing v7.0 (SP-0) with VerifyVersionInfoW()
	--> NOT supported!
	Testing v8.0 (SP-0) with VerifyVersionInfoW()
	--> NOT supported!
	Testing v9.0 (SP-0) with VerifyVersionInfoW()
	--> NOT supported!
	Testing v10.0 (SP-0) with VerifyVersionInfoW()
	--> NOT supported!
	Testing v6.3 (SP-0) with VerifyVersionInfoW()
	--> NOT supported!
	Testing v6.2 (SP-1) with VerifyVersionInfoW()
	--> NOT supported!

	Completed: Running on Windows v6.2 (SP-0)

**Comment by lordmulder** [comment]
Here is a new version with workaround for Windows 10 detection:
https://github.com/lordmulder/stdutils/releases/tag/1.06

**Comment by pschrijver** [comment]
Tested 1.06 on every Windows from XP up to 10 build 10130, and it's working perfectly.
Thanks a lot, much appreciated.

**Comment by tpoechtrager** [comment]
For visitors who may find this via Google:

There is still a way to get the true version without checking the file version of `kernel32.dll`. See https://stackoverflow.com/a/36545162/1392778 for more.

**Comment by lordmulder** [comment]
> For visitors who may find this via Google:
>
> There is still a way to get the true version without checking the file version of `kernel32.dll`. See > https://stackoverflow.com/a/36545162/1392778 for more.

That's exactly what we have been doing for quite some time now:
https://github.com/lordmulder/stdutils/blob/65e3316e0cdf3a41aeea73821f9fe470accd9a9e/Contrib/StdUtils/src/DetectOsVersion.cpp#L447-L467
